<?php

/**
 * @file
 * Contains warehouse.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function warehouse_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the warehouse module.
    case 'help.page.warehouse':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Warehouse Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function warehouse_theme() {
  return [
    'warehouse' => [
      'render element' => 'children',
    ],
  ];
}
