<?php

/**
 * @file
 * Contains report.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function report_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the report module.
    case 'help.page.report':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Report') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function report_theme() {
  return [
    'report' => [
      'render element' => 'children',
    ],
  ];
}
