<?php

/**
 * @file
 * Contains api.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the api module.
    case 'help.page.api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Miasuki API') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function api_theme() {
  return [
    'api' => [
      'render element' => 'children',
    ],
  ];
}
