<?php

/**
 * @file
 * Contains order.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function order_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the order module.
    case 'help.page.order':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Miasuki Order') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function order_theme() {
  return [
    'order' => [
      'render element' => 'children',
    ],
  ];
}
